name: myapp
description: 


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/pembeli/images/vector.png
    - assets/penjual/images/vector-5.png
    - assets/penjual/images/ellipse-2.png
    - assets/pembeli/images/vector-AGv.png
    - assets/penjual/images/ellipse-2-TpS.png
    - assets/pembeli/images/auto-group-bn2a.png
    - assets/pembeli/images/vector-tP8.png
    - assets/penjual/images/vector-5-bQS.png
    - assets/pembeli/images/widget.png
    - assets/penjual/images/vector-FSN.png
    - assets/card/images/ellipse-2-4HL.png
    - assets/card/images/vector-5-yae.png
    - assets/card/images/vector-5-3gA.png
    - assets/card/images/trash.png
    - assets/pembeli/images/ellipse-2-6mU.png
    - assets/pembeli/images/ellipse-2-FSe.png
    - assets/pembeli/images/ellipse-2-VD8.png
    - assets/penjual/images/vector-k4W.png
    - assets/card/images/auto-group-1css.png
    - assets/card/images/vector-Gkn.png
    - assets/penjual/images/vector-5-BEn.png
    - assets/penjual/images/vector-w2v.png
    - assets/pembeli/images/vector-5-BHx.png
    - assets/pembeli/images/trash-8iz.png
    - assets/penjual/images/vector-7rN.png
    - assets/penjual/images/ellipse-2-TfL.png
    - assets/penjual/images/vector-5-9xi.png
    - assets/pembeli/images/auto-group-5oy8.png
    - assets/pembeli/images/notif-button.png
    - assets/pembeli/images/vector-5-UeA.png
    - assets/pembeli/images/vector-8u4.png
    - assets/card/images/vector-B2e.png
    - assets/pembeli/images/trash-xgv.png
    - assets/pembeli/images/ellipse-2-xXg.png
    - assets/card/images/ellipse-2-ySn.png
    - assets/penjual/images/vector-q18.png
    - assets/penjual/images/vector-5-aUW.png
    - assets/penjual/images/vector-dQA.png
    - assets/pembeli/images/auto-group-abla.png
    - assets/pembeli/images/trash-PE6.png
    - assets/penjual/images/ellipse-2-g78.png
    - assets/pembeli/images/vector-5-4Wa.png
    - assets/pembeli/images/vector-JNA.png
    - assets/pembeli/images/ellipse-2-j6e.png
    - assets/pembeli/images/vector-tXG.png
    - assets/penjual/images/ellipse-2-d1Y.png
    - assets/pembeli/images/auto-group-fadl.png
    - assets/pembeli/images/vector-SLE.png
    - assets/penjual/images/vector-xJa.png
    - assets/pembeli/images/vector-5-tfG.png
    - assets/pembeli/images/ellipse-2-pzi.png
    - assets/pembeli/images/auto-group-bewg.png
    - assets/pembeli/images/ellipse-2-Eer.png
    - assets/penjual/images/vector-SJA.png
    - assets/penjual/images/vector-QtW.png
    - assets/penjual/images/ellipse-2-BzN.png
    - assets/penjual/images/vector-5-5ux.png
    - assets/penjual/images/vector-GWa.png
    - assets/pembeli/images/ellipse-2-Yva.png
    - assets/pembeli/images/auto-group-kykc.png
    - assets/pembeli/images/auto-group-u24w.png
    - assets/penjual/images/vector-Jvr.png
    - assets/penjual/images/vector-nut.png
    - assets/card/images/ellipse-2-wkA.png
    - assets/penjual/images/vector-4Zt.png
    - assets/penjual/images/vector-SAS.png
    - assets/penjual/images/vector-V6e.png
    - assets/penjual/images/vector-bhQ.png
    - assets/penjual/images/ellipse-2-1Qz.png
    - assets/pembeli/images/vector-5-BmY.png
    - assets/penjual/images/vector-FRG.png
    - assets/penjual/images/vector-5-L7G.png
    - assets/card/images/auto-group-gzt6.png
    - assets/pembeli/images/ellipse-2-7pa.png
    - assets/penjual/images/vector-Nxn.png
    - assets/card/images/vector-5-cs8.png
    - assets/penjual/images/ellipse-2-weW.png
    - assets/penjual/images/vector-5-5Xk.png
    - assets/penjual/images/vector-J7x.png
    - assets/pembeli/images/vector-x8E.png
    - assets/pembeli/images/vector-5-b4i.png
    - assets/pembeli/images/rectangle-3-bg.png
    - assets/pembeli/images/rectangle-6-bg.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
